<?xml version="1.0" encoding="UTF-8"?>
<testsuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd" name="Entity.TestDB.EmployeeCrudTest" time="5.199" tests="8" errors="4" skipped="0" failures="4">
  <properties>
    <property name="java.runtime.name" value="Java(TM) SE Runtime Environment"/>
    <property name="sun.boot.library.path" value="/home/deecarneiro/jdk1.8.0_111/jre/lib/amd64"/>
    <property name="java.vm.version" value="25.111-b14"/>
    <property name="java.vm.vendor" value="Oracle Corporation"/>
    <property name="java.vendor.url" value="http://java.oracle.com/"/>
    <property name="path.separator" value=":"/>
    <property name="guice.disable.misplaced.annotation.check" value="true"/>
    <property name="java.vm.name" value="Java HotSpot(TM) 64-Bit Server VM"/>
    <property name="file.encoding.pkg" value="sun.io"/>
    <property name="user.country" value="BR"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="sun.os.patch.level" value="unknown"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="user.dir" value="/home/deecarneiro/Área de Trabalho/TADS/DuctumEJB"/>
    <property name="java.runtime.version" value="1.8.0_111-b14"/>
    <property name="netbeans.deploy" value="true"/>
    <property name="java.awt.graphicsenv" value="sun.awt.X11GraphicsEnvironment"/>
    <property name="java.endorsed.dirs" value="/home/deecarneiro/jdk1.8.0_111/jre/lib/endorsed"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.io.tmpdir" value="/tmp"/>
    <property name="line.separator" value="&#10;"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="os.name" value="Linux"/>
    <property name="maven.ext.class.path" value="/home/deecarneiro/netbeans-8.2/java/maven-nblib/netbeans-eventspy.jar"/>
    <property name="classworlds.conf" value="/home/deecarneiro/netbeans-8.2/java/maven/bin/m2.conf"/>
    <property name="sun.jnu.encoding" value="UTF-8"/>
    <property name="java.library.path" value="/home/deecarneiro/jdk1.8.0_111/jre/lib/amd64:/home/deecarneiro/jdk1.8.0_111/jre/lib/i386::/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="java.class.version" value="52.0"/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="os.version" value="5.0.0-36-generic"/>
    <property name="user.home" value="/home/deecarneiro"/>
    <property name="user.timezone" value="America/Recife"/>
    <property name="java.awt.printerjob" value="sun.print.PSPrinterJob"/>
    <property name="java.specification.version" value="1.8"/>
    <property name="file.encoding" value="UTF-8"/>
    <property name="user.name" value="deecarneiro"/>
    <property name="java.class.path" value="/home/deecarneiro/netbeans-8.2/java/maven/boot/plexus-classworlds-2.4.jar"/>
    <property name="java.vm.specification.version" value="1.8"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="java.home" value="/home/deecarneiro/jdk1.8.0_111/jre"/>
    <property name="sun.java.command" value="org.codehaus.plexus.classworlds.launcher.Launcher -Dnetbeans.deploy=true -Dmaven.ext.class.path=/home/deecarneiro/netbeans-8.2/java/maven-nblib/netbeans-eventspy.jar package"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="user.language" value="pt"/>
    <property name="awt.toolkit" value="sun.awt.X11.XToolkit"/>
    <property name="java.vm.info" value="mixed mode"/>
    <property name="java.version" value="1.8.0_111"/>
    <property name="java.ext.dirs" value="/home/deecarneiro/jdk1.8.0_111/jre/lib/ext:/usr/java/packages/lib/ext"/>
    <property name="securerandom.source" value="file:/dev/./urandom"/>
    <property name="sun.boot.class.path" value="/home/deecarneiro/jdk1.8.0_111/jre/lib/resources.jar:/home/deecarneiro/jdk1.8.0_111/jre/lib/rt.jar:/home/deecarneiro/jdk1.8.0_111/jre/lib/sunrsasign.jar:/home/deecarneiro/jdk1.8.0_111/jre/lib/jsse.jar:/home/deecarneiro/jdk1.8.0_111/jre/lib/jce.jar:/home/deecarneiro/jdk1.8.0_111/jre/lib/charsets.jar:/home/deecarneiro/jdk1.8.0_111/jre/lib/jfr.jar:/home/deecarneiro/jdk1.8.0_111/jre/classes"/>
    <property name="java.vendor" value="Oracle Corporation"/>
    <property name="maven.home" value="/home/deecarneiro/netbeans-8.2/java/maven"/>
    <property name="file.separator" value="/"/>
    <property name="java.vendor.url.bug" value="http://bugreport.sun.com/bugreport/"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="sun.desktop" value="gnome"/>
    <property name="sun.cpu.isalist" value=""/>
  </properties>
  <testcase name="persistirEmployee" classname="Entity.TestDB.EmployeeCrudTest" time="0.008">
    <error message="Exception [EclipseLink-7060] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.ValidationException&#10;Exception Description: Cannot acquire data source [jdbc/ductum].&#10;Internal Exception: javax.naming.NamingException: Lookup failed for &apos;jdbc/ductum&apos; in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl} [Root exception is javax.naming.NameNotFoundException: ductum not found]" type="javax.persistence.PersistenceException">javax.persistence.PersistenceException: 
Exception [EclipseLink-7060] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.ValidationException
Exception Description: Cannot acquire data source [jdbc/ductum].
Internal Exception: javax.naming.NamingException: Lookup failed for 'jdbc/ductum' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl} [Root exception is javax.naming.NameNotFoundException: ductum not found]
Caused by: org.eclipse.persistence.exceptions.ValidationException: 

Exception Description: Cannot acquire data source [jdbc/ductum].
Internal Exception: javax.naming.NamingException: Lookup failed for 'jdbc/ductum' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl} [Root exception is javax.naming.NameNotFoundException: ductum not found]
Caused by: javax.naming.NamingException: Lookup failed for 'jdbc/ductum' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl}
Caused by: javax.naming.NameNotFoundException: ductum not found
</error>
    <system-out><![CDATA[[EL Config]: metadata: 2019-11-25 01:55:44.687--ServerSession(1206820936)--Thread(Thread[main,5,main])--The access type for the persistent class [class com.mycompany.ductumejb.entidade.Entidade] is set to [FIELD].
[EL Config]: metadata: 2019-11-25 01:55:44.687--ServerSession(1206820936)--Thread(Thread[main,5,main])--The target entity (reference) class for the many to one mapping element [field project] is being defaulted to: class com.mycompany.ductumejb.entidade.Project.
[EL Config]: metadata: 2019-11-25 01:55:44.687--ServerSession(1206820936)--Thread(Thread[main,5,main])--The access type for the persistent class [class com.mycompany.ductumejb.entidade.Client] is set to [FIELD].
[EL Config]: metadata: 2019-11-25 01:55:44.688--ServerSession(1206820936)--Thread(Thread[main,5,main])--The target entity (reference) class for the many to many mapping element [field solicitations] is being defaulted to: class com.mycompany.ductumejb.entidade.Solicitation.
[EL Config]: metadata: 2019-11-25 01:55:44.688--ServerSession(1206820936)--Thread(Thread[main,5,main])--The access type for the persistent class [class com.mycompany.ductumejb.entidade.Sprint] is set to [FIELD].
[EL Config]: metadata: 2019-11-25 01:55:44.688--ServerSession(1206820936)--Thread(Thread[main,5,main])--The target entity (reference) class for the one to many mapping element [field features] is being defaulted to: class com.mycompany.ductumejb.entidade.Feature.
[EL Config]: metadata: 2019-11-25 01:55:44.688--ServerSession(1206820936)--Thread(Thread[main,5,main])--The target entity (reference) class for the many to one mapping element [field project] is being defaulted to: class com.mycompany.ductumejb.entidade.Project.
[EL Config]: metadata: 2019-11-25 01:55:44.688--ServerSession(1206820936)--Thread(Thread[main,5,main])--The access type for the persistent class [class com.mycompany.ductumejb.entidade.Employee] is set to [FIELD].
[EL Config]: metadata: 2019-11-25 01:55:44.688--ServerSession(1206820936)--Thread(Thread[main,5,main])--The access type for the persistent class [class com.mycompany.ductumejb.entidade.Comment] is set to [FIELD].
[EL Config]: metadata: 2019-11-25 01:55:44.688--ServerSession(1206820936)--Thread(Thread[main,5,main])--The target entity (reference) class for the one to one mapping element [field user] is being defaulted to: class com.mycompany.ductumejb.entidade.Employee.
[EL Config]: metadata: 2019-11-25 01:55:44.688--ServerSession(1206820936)--Thread(Thread[main,5,main])--The access type for the persistent class [class com.mycompany.ductumejb.entidade.Meeting] is set to [FIELD].
[EL Config]: metadata: 2019-11-25 01:55:44.688--ServerSession(1206820936)--Thread(Thread[main,5,main])--The target entity (reference) class for the many to one mapping element [field sprint] is being defaulted to: class com.mycompany.ductumejb.entidade.Sprint.
[EL Config]: metadata: 2019-11-25 01:55:44.689--ServerSession(1206820936)--Thread(Thread[main,5,main])--The access type for the persistent class [class com.mycompany.ductumejb.entidade.Feature] is set to [FIELD].
[EL Config]: metadata: 2019-11-25 01:55:44.689--ServerSession(1206820936)--Thread(Thread[main,5,main])--The target entity (reference) class for the one to many mapping element [field comments] is being defaulted to: class com.mycompany.ductumejb.entidade.Comment.
[EL Config]: metadata: 2019-11-25 01:55:44.689--ServerSession(1206820936)--Thread(Thread[main,5,main])--The target entity (reference) class for the one to one mapping element [field responsible] is being defaulted to: class com.mycompany.ductumejb.entidade.Employee.
[EL Config]: metadata: 2019-11-25 01:55:44.689--ServerSession(1206820936)--Thread(Thread[main,5,main])--The target entity (reference) class for the many to one mapping element [field reporter] is being defaulted to: class com.mycompany.ductumejb.entidade.Employee.
[EL Config]: metadata: 2019-11-25 01:55:44.689--ServerSession(1206820936)--Thread(Thread[main,5,main])--The target entity (reference) class for the one to one mapping element [field responsible] is being defaulted to: class com.mycompany.ductumejb.entidade.Employee.
[EL Config]: metadata: 2019-11-25 01:55:44.689--ServerSession(1206820936)--Thread(Thread[main,5,main])--The target entity (reference) class for the many to one mapping element [field client] is being defaulted to: class com.mycompany.ductumejb.entidade.Client.
[EL Config]: metadata: 2019-11-25 01:55:44.689--ServerSession(1206820936)--Thread(Thread[main,5,main])--The target entity (reference) class for the many to many mapping element [field employees] is being defaulted to: class com.mycompany.ductumejb.entidade.Employee.
[EL Config]: metadata: 2019-11-25 01:55:44.689--ServerSession(1206820936)--Thread(Thread[main,5,main])--The alias name for the entity class [class com.mycompany.ductumejb.entidade.Solicitation] is being defaulted to: Solicitation.
[EL Config]: metadata: 2019-11-25 01:55:44.69--ServerSession(1206820936)--Thread(Thread[main,5,main])--The alias name for the entity class [class com.mycompany.ductumejb.entidade.Client] is being defaulted to: Client.
[EL Config]: metadata: 2019-11-25 01:55:44.69--ServerSession(1206820936)--Thread(Thread[main,5,main])--The alias name for the entity class [class com.mycompany.ductumejb.entidade.UserSuper] is being defaulted to: UserSuper.
[EL Config]: metadata: 2019-11-25 01:55:44.69--ServerSession(1206820936)--Thread(Thread[main,5,main])--The alias name for the entity class [class com.mycompany.ductumejb.entidade.Sprint] is being defaulted to: Sprint.
[EL Config]: metadata: 2019-11-25 01:55:44.69--ServerSession(1206820936)--Thread(Thread[main,5,main])--The alias name for the entity class [class com.mycompany.ductumejb.entidade.Employee] is being defaulted to: Employee.
[EL Config]: metadata: 2019-11-25 01:55:44.69--ServerSession(1206820936)--Thread(Thread[main,5,main])--The column name for element [cpf] is being defaulted to: CPF.
[EL Config]: metadata: 2019-11-25 01:55:44.691--ServerSession(1206820936)--Thread(Thread[main,5,main])--The alias name for the entity class [class com.mycompany.ductumejb.entidade.Comment] is being defaulted to: Comment.
[EL Config]: metadata: 2019-11-25 01:55:44.691--ServerSession(1206820936)--Thread(Thread[main,5,main])--The alias name for the entity class [class com.mycompany.ductumejb.entidade.Meeting] is being defaulted to: Meeting.
[EL Config]: metadata: 2019-11-25 01:55:44.691--ServerSession(1206820936)--Thread(Thread[main,5,main])--The alias name for the entity class [class com.mycompany.ductumejb.entidade.Feature] is being defaulted to: Feature.
[EL Config]: metadata: 2019-11-25 01:55:44.691--ServerSession(1206820936)--Thread(Thread[main,5,main])--The alias name for the entity class [class com.mycompany.ductumejb.entidade.Project] is being defaulted to: Project.
[EL Config]: metadata: 2019-11-25 01:55:44.691--ServerSession(1206820936)--Thread(Thread[main,5,main])--The primary key column name for the mapping element [field project] is being defaulted to: ID.
[EL Config]: metadata: 2019-11-25 01:55:44.691--ServerSession(1206820936)--Thread(Thread[main,5,main])--The source primary key column name for the many to many mapping [field solicitations] is being defaulted to: ID.
[EL Config]: metadata: 2019-11-25 01:55:44.692--ServerSession(1206820936)--Thread(Thread[main,5,main])--The target primary key column name for the many to many mapping [field solicitations] is being defaulted to: ID.
[EL Config]: metadata: 2019-11-25 01:55:44.692--ServerSession(1206820936)--Thread(Thread[main,5,main])--The primary key column name for the mapping element [field features] is being defaulted to: ID.
[EL Config]: metadata: 2019-11-25 01:55:44.692--ServerSession(1206820936)--Thread(Thread[main,5,main])--The primary key column name for the mapping element [field project] is being defaulted to: ID.
[EL Config]: metadata: 2019-11-25 01:55:44.692--ServerSession(1206820936)--Thread(Thread[main,5,main])--The primary key column name for the mapping element [field sprint] is being defaulted to: ID.
[EL Config]: metadata: 2019-11-25 01:55:44.692--ServerSession(1206820936)--Thread(Thread[main,5,main])--The primary key column name for the mapping element [field comments] is being defaulted to: ID.
[EL Config]: metadata: 2019-11-25 01:55:44.692--ServerSession(1206820936)--Thread(Thread[main,5,main])--The primary key column name for the mapping element [field reporter] is being defaulted to: ID.
[EL Config]: metadata: 2019-11-25 01:55:44.692--ServerSession(1206820936)--Thread(Thread[main,5,main])--The primary key column name for the mapping element [field client] is being defaulted to: ID.
[EL Config]: metadata: 2019-11-25 01:55:44.693--ServerSession(1206820936)--Thread(Thread[main,5,main])--The source primary key column name for the many to many mapping [field employees] is being defaulted to: ID.
[EL Config]: metadata: 2019-11-25 01:55:44.693--ServerSession(1206820936)--Thread(Thread[main,5,main])--The target primary key column name for the many to many mapping [field employees] is being defaulted to: ID.
[EL Info]: 2019-11-25 01:55:49.922--ServerSession(1206820936)--Thread(Thread[main,5,main])--EclipseLink, version: Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd
[EL Config]: connection: 2019-11-25 01:55:49.922--ServerSession(1206820936)--Connection(417584871)--Thread(Thread[main,5,main])--connecting(DatabaseLogin(
	platform=>MySQLPlatform
	user name=> "root"
	connector=>JNDIConnector datasource name=>jdbc/ductum
))
[EL Severe]: 2019-11-25 01:55:49.923--ServerSession(1206820936)--Thread(Thread[main,5,main])--Exception [EclipseLink-7060] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.ValidationException
Exception Description: Cannot acquire data source [jdbc/ductum].
Internal Exception: javax.naming.NamingException: Lookup failed for 'jdbc/ductum' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl} [Root exception is javax.naming.NameNotFoundException: ductum not found]
[EL Severe]: ejb: 2019-11-25 01:55:49.923--ServerSession(1206820936)--Thread(Thread[main,5,main])--Exception [EclipseLink-7060] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.ValidationException
Exception Description: Cannot acquire data source [jdbc/ductum].
Internal Exception: javax.naming.NamingException: Lookup failed for 'jdbc/ductum' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl} [Root exception is javax.naming.NameNotFoundException: ductum not found]
]]></system-out>
    <system-err><![CDATA[nov 25, 2019 1:55:49 AM Entity.TestDB.GenericTest commitTransaction
GRAVE: null
java.lang.NullPointerException
	at Entity.TestDB.GenericTest.commitTransaction(GenericTest.java:66)
	at Entity.TestDB.GenericTest.tearDown(GenericTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)

]]></system-err>
  </testcase>
  <testcase name="persistirEmployee" classname="Entity.TestDB.EmployeeCrudTest" time="0.008">
    <failure type="java.lang.AssertionError">java.lang.AssertionError
</failure>
  </testcase>
  <testcase name="atualizarEmployee" classname="Entity.TestDB.EmployeeCrudTest" time="0.001">
    <error message="Exception [EclipseLink-7060] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.ValidationException&#10;Exception Description: Cannot acquire data source [jdbc/ductum].&#10;Internal Exception: javax.naming.NamingException: Lookup failed for &apos;jdbc/ductum&apos; in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl} [Root exception is javax.naming.NameNotFoundException: ductum not found]" type="javax.persistence.PersistenceException">javax.persistence.PersistenceException: 
Exception [EclipseLink-7060] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.ValidationException
Exception Description: Cannot acquire data source [jdbc/ductum].
Internal Exception: javax.naming.NamingException: Lookup failed for 'jdbc/ductum' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl} [Root exception is javax.naming.NameNotFoundException: ductum not found]
Caused by: org.eclipse.persistence.exceptions.ValidationException: 

Exception Description: Cannot acquire data source [jdbc/ductum].
Internal Exception: javax.naming.NamingException: Lookup failed for 'jdbc/ductum' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl} [Root exception is javax.naming.NameNotFoundException: ductum not found]
Caused by: javax.naming.NamingException: Lookup failed for 'jdbc/ductum' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl}
Caused by: javax.naming.NameNotFoundException: ductum not found
</error>
    <system-out><![CDATA[[EL Info]: 2019-11-25 01:55:49.924--ServerSession(1206820936)--Thread(Thread[main,5,main])--EclipseLink, version: Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd
[EL Config]: connection: 2019-11-25 01:55:49.924--ServerSession(1206820936)--Connection(2067080518)--Thread(Thread[main,5,main])--connecting(DatabaseLogin(
	platform=>MySQLPlatform
	user name=> "root"
	connector=>JNDIConnector datasource name=>jdbc/ductum
))
[EL Severe]: 2019-11-25 01:55:49.924--ServerSession(1206820936)--Thread(Thread[main,5,main])--Exception [EclipseLink-7060] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.ValidationException
Exception Description: Cannot acquire data source [jdbc/ductum].
Internal Exception: javax.naming.NamingException: Lookup failed for 'jdbc/ductum' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl} [Root exception is javax.naming.NameNotFoundException: ductum not found]
[EL Severe]: ejb: 2019-11-25 01:55:49.925--ServerSession(1206820936)--Thread(Thread[main,5,main])--Exception [EclipseLink-7060] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.ValidationException
Exception Description: Cannot acquire data source [jdbc/ductum].
Internal Exception: javax.naming.NamingException: Lookup failed for 'jdbc/ductum' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl} [Root exception is javax.naming.NameNotFoundException: ductum not found]
]]></system-out>
    <system-err><![CDATA[nov 25, 2019 1:55:49 AM Entity.TestDB.GenericTest commitTransaction
GRAVE: null
java.lang.NullPointerException
	at Entity.TestDB.GenericTest.commitTransaction(GenericTest.java:66)
	at Entity.TestDB.GenericTest.tearDown(GenericTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)

]]></system-err>
  </testcase>
  <testcase name="atualizarEmployee" classname="Entity.TestDB.EmployeeCrudTest" time="0.001">
    <failure type="java.lang.AssertionError">java.lang.AssertionError
</failure>
  </testcase>
  <testcase name="atualizarEmployeeMerge" classname="Entity.TestDB.EmployeeCrudTest" time="0.014">
    <error message="Exception [EclipseLink-7060] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.ValidationException&#10;Exception Description: Cannot acquire data source [jdbc/ductum].&#10;Internal Exception: javax.naming.NamingException: Lookup failed for &apos;jdbc/ductum&apos; in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl} [Root exception is javax.naming.NameNotFoundException: ductum not found]" type="javax.persistence.PersistenceException">javax.persistence.PersistenceException: 
Exception [EclipseLink-7060] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.ValidationException
Exception Description: Cannot acquire data source [jdbc/ductum].
Internal Exception: javax.naming.NamingException: Lookup failed for 'jdbc/ductum' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl} [Root exception is javax.naming.NameNotFoundException: ductum not found]
Caused by: org.eclipse.persistence.exceptions.ValidationException: 

Exception Description: Cannot acquire data source [jdbc/ductum].
Internal Exception: javax.naming.NamingException: Lookup failed for 'jdbc/ductum' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl} [Root exception is javax.naming.NameNotFoundException: ductum not found]
Caused by: javax.naming.NamingException: Lookup failed for 'jdbc/ductum' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl}
Caused by: javax.naming.NameNotFoundException: ductum not found
</error>
    <system-out><![CDATA[[EL Info]: 2019-11-25 01:55:49.926--ServerSession(1206820936)--Thread(Thread[main,5,main])--EclipseLink, version: Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd
[EL Config]: connection: 2019-11-25 01:55:49.926--ServerSession(1206820936)--Connection(1431739829)--Thread(Thread[main,5,main])--connecting(DatabaseLogin(
	platform=>MySQLPlatform
	user name=> "root"
	connector=>JNDIConnector datasource name=>jdbc/ductum
))
[EL Severe]: 2019-11-25 01:55:49.926--ServerSession(1206820936)--Thread(Thread[main,5,main])--Exception [EclipseLink-7060] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.ValidationException
Exception Description: Cannot acquire data source [jdbc/ductum].
Internal Exception: javax.naming.NamingException: Lookup failed for 'jdbc/ductum' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl} [Root exception is javax.naming.NameNotFoundException: ductum not found]
[EL Severe]: ejb: 2019-11-25 01:55:49.926--ServerSession(1206820936)--Thread(Thread[main,5,main])--Exception [EclipseLink-7060] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.ValidationException
Exception Description: Cannot acquire data source [jdbc/ductum].
Internal Exception: javax.naming.NamingException: Lookup failed for 'jdbc/ductum' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl} [Root exception is javax.naming.NameNotFoundException: ductum not found]
]]></system-out>
    <system-err><![CDATA[nov 25, 2019 1:55:49 AM Entity.TestDB.GenericTest commitTransaction
GRAVE: null
java.lang.NullPointerException
	at Entity.TestDB.GenericTest.commitTransaction(GenericTest.java:66)
	at Entity.TestDB.GenericTest.tearDown(GenericTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)

]]></system-err>
  </testcase>
  <testcase name="atualizarEmployeeMerge" classname="Entity.TestDB.EmployeeCrudTest" time="0.014">
    <failure type="java.lang.AssertionError">java.lang.AssertionError
</failure>
  </testcase>
  <testcase name="removerEmployee" classname="Entity.TestDB.EmployeeCrudTest" time="0.004">
    <error message="Exception [EclipseLink-7060] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.ValidationException&#10;Exception Description: Cannot acquire data source [jdbc/ductum].&#10;Internal Exception: javax.naming.NamingException: Lookup failed for &apos;jdbc/ductum&apos; in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl} [Root exception is javax.naming.NameNotFoundException: ductum not found]" type="javax.persistence.PersistenceException">javax.persistence.PersistenceException: 
Exception [EclipseLink-7060] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.ValidationException
Exception Description: Cannot acquire data source [jdbc/ductum].
Internal Exception: javax.naming.NamingException: Lookup failed for 'jdbc/ductum' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl} [Root exception is javax.naming.NameNotFoundException: ductum not found]
Caused by: org.eclipse.persistence.exceptions.ValidationException: 

Exception Description: Cannot acquire data source [jdbc/ductum].
Internal Exception: javax.naming.NamingException: Lookup failed for 'jdbc/ductum' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl} [Root exception is javax.naming.NameNotFoundException: ductum not found]
Caused by: javax.naming.NamingException: Lookup failed for 'jdbc/ductum' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl}
Caused by: javax.naming.NameNotFoundException: ductum not found
</error>
    <system-out><![CDATA[[EL Info]: 2019-11-25 01:55:49.941--ServerSession(1206820936)--Thread(Thread[main,5,main])--EclipseLink, version: Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd
[EL Config]: connection: 2019-11-25 01:55:49.941--ServerSession(1206820936)--Connection(616345872)--Thread(Thread[main,5,main])--connecting(DatabaseLogin(
	platform=>MySQLPlatform
	user name=> "root"
	connector=>JNDIConnector datasource name=>jdbc/ductum
))
[EL Severe]: 2019-11-25 01:55:49.942--ServerSession(1206820936)--Thread(Thread[main,5,main])--Exception [EclipseLink-7060] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.ValidationException
Exception Description: Cannot acquire data source [jdbc/ductum].
Internal Exception: javax.naming.NamingException: Lookup failed for 'jdbc/ductum' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl} [Root exception is javax.naming.NameNotFoundException: ductum not found]
[EL Severe]: ejb: 2019-11-25 01:55:49.942--ServerSession(1206820936)--Thread(Thread[main,5,main])--Exception [EclipseLink-7060] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.ValidationException
Exception Description: Cannot acquire data source [jdbc/ductum].
Internal Exception: javax.naming.NamingException: Lookup failed for 'jdbc/ductum' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl} [Root exception is javax.naming.NameNotFoundException: ductum not found]
]]></system-out>
    <system-err><![CDATA[nov 25, 2019 1:55:49 AM Entity.TestDB.GenericTest commitTransaction
GRAVE: null
java.lang.NullPointerException
	at Entity.TestDB.GenericTest.commitTransaction(GenericTest.java:66)
	at Entity.TestDB.GenericTest.tearDown(GenericTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)

]]></system-err>
  </testcase>
  <testcase name="removerEmployee" classname="Entity.TestDB.EmployeeCrudTest" time="0.004">
    <failure type="java.lang.AssertionError">java.lang.AssertionError
</failure>
  </testcase>
</testsuite>